my-external-code-path/config/routes.rb
Rails.application.routes.draw do
  resources :rooms do
    resources :messages
  end

  root to: "rooms#index"
end

my-external-code-path/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

my-external-code-path/app/models/message.rb
class Message < ApplicationRecord
  belongs_to :room
  broadcasts_to :room
end

my-external-code-path/app/models/room.rb
class Room < ApplicationRecord
  has_many :messages, dependent: :destroy
  broadcasts
end

my-external-code-path/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

my-external-code-path/app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :set_room, only: %i[ new create ]

  def new
    @message = @room.messages.new
  end

  def create
    @message = @room.messages.create!(message_params)

    respond_to do |format|
      format.turbo_stream
      format.html { redirect_to @room }
    end
  end

  private
    def set_room
      @room = Room.find(params[:room_id])
    end

    def message_params
      params.require(:message).permit(:content)
    end
end

my-external-code-path/app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :set_room, only: %i[ show edit update destroy ]

  def index
    @rooms = Room.all
  end

  def show
  end

  def new
    @room = Room.new
  end

  def edit
  end

  def create
    @room = Room.create!(room_params)
    redirect_to @room, notice: 'Room was successfully created.'
  end

  def update
    @room.update!(room_params)
    redirect_to @room, notice: 'Room was successfully updated.'
  end

  def destroy
    @room.destroy
    redirect_to rooms_url, notice: 'Room was successfully destroyed.'
  end

  private
    def set_room
      @room = Room.find(params[:id])
    end

    def room_params
      params.require(:room).permit(:name)
    end
end

my-external-code-path/app/helpers/application_helper.rb
module ApplicationHelper
end

my-external-code-path/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Chat</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= yield :head %>
    <%= turbo_include_tags %>
    <%= stimulus_include_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

my-external-code-path/app/views/messages/_message.html.erb
<p id="<%= dom_id message %>">
  <%= message.created_at.to_s(:short) %>: <%= message.content %>
</p>

my-external-code-path/app/views/messages/create.turbo_stream.erb
<% # Return handled by cable %>

my-external-code-path/app/views/messages/new.html.erb
<h1>New Message</h1>

<%= turbo_frame_tag "new_message", target: "_top" do %>
  <%= form_with(model: [ @message.room, @message ],
        data: { controller: "reset_form", action: "turbo:submit-end->reset_form#reset" }) do |form| %>
    <div class="field">
      <%= form.text_field :content %>
      <%= form.submit "Send" %>
    </div>
  <% end %>
<% end %>

<%= link_to 'Back', @message.room %>

my-external-code-path/app/views/rooms/_form.html.erb
<%= form_with(model: room) do |form| %>
  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

my-external-code-path/app/views/rooms/_room.html.erb
<p id="<%= dom_id room %>">
  <strong>Name:</strong>
  <%= room.name %>
</p>

my-external-code-path/app/views/rooms/edit.html.erb
<h1>Editing Room</h1>

<%= turbo_frame_tag "room" do %>
  <%= render 'form', room: @room %>
<% end %>

<%= link_to 'Show', @room %> |
<%= link_to 'Back', rooms_path %>

my-external-code-path/app/views/rooms/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Rooms</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @rooms.each do |room| %>
      <tr>
        <td><%= room.name %></td>
        <td><%= link_to 'Show', room %></td>
        <td><%= link_to 'Edit', edit_room_path(room) %></td>
        <td><%= link_to 'Destroy', room, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Room', new_room_path %>

my-external-code-path/app/views/rooms/new.html.erb
<h1>New Room</h1>

<%= render 'form', room: @room %>

<%= link_to 'Back', rooms_path %>

my-external-code-path/app/views/rooms/show.html.erb
<p id="notice"><%= notice %></p>

<%= turbo_stream_from @room %>

<%= turbo_frame_tag "room" do %>
  <%= render @room %>

  <p>
    <%= link_to 'Edit', edit_room_path(@room) %> |
    <%= link_to 'Back', rooms_path, "data-turbo-frame": "_top" %>
  </p>
<% end %>

<div id="messages">
  <%= render @room.messages %>
</div>

<%= turbo_frame_tag "new_message", src: new_room_message_path(@room), target: "_top" %>